### ISSUE TITLE
PnP - Community Docs Contributor Sessions - June 26th & 29th

### ISSUE THREAD

**Issue by PopWarner** [pnp/sharing-is-caring#114]
Hello PnP Contributors! 😉

If you would like to join a PnP Sharing Is Caring - Community Docs Contributor guidance session, please use the link below to select one of the scheduled sessions.

**June 26th & 29th - Sharing is Caring - Community Docs Contributor Registration:**
https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdURVNQSUcwWFVRT1dWNUUyUFBGRzM2VjJGQi4u

We know that schedules vary...so if you are unable to the sessions, not to worry!! There are more sessions scheduled each month. 😊

Thanks again for your collaborative community spirit!! 👍

**_You can also find all of the available scheduled sessions at:
https://aka.ms/sharing-is-caring#pnp-sic-events_**

cc: @hugoabernier

**Comment by PopWarner** [comment]
Thank you to all who have registered. A Microsoft Teams calendar invite has been sent out to all that have registered. Occasionally the invite will get placed into the spam, junk or bulk boxes, so if you don't see the invite, try double checking those boxes. 🙂

Please don't hesitate to reach out if you have not received the email invite. 🙂💜🧡

We look forward to seeing you all!!

@sinhakislay
@rahulsuryawanshi
@LJ-Boogie
@marcjordana

**Comment by sinhakislay** [comment]
Hi David,

I remember there were two slots for the session, it seems I selected the wrong one as the current one for me will be at 11 PM in the night.

Do you have the possibility to adjust me in the another slot?

Please let me know.
Thanks,
Kislay
________________________________

**Comment by rahulsuryawanshi** [comment]
Hi David,
Thanks. I have received the invite and accepted it. Excited to join the session!

Thanks
Rahul

**Comment by PopWarner** [comment]
@sinhakislay, no problem. I'll reach out to you directly to find which one you would like to be switched over to. 😁

**Comment by PopWarner** [comment]
Thank you for registering. You have been added to your chosen the session. A Microsoft Teams calendar invite has been sent out to all that have registered. Occasionally the invite will get placed into the spam, junk or bulk boxes, so if you don't see the invite, try double checking those boxes. 🙂

Please don't hesitate to reach out if you have not received the email invite. 🙂💜🧡

@anicholson9
@annajhaveri
@ViewPorter
@JarbasHorst
@kirti-prajapati
@LJ-Boogie
@Jenny-Neal
@FunctionOne
@westerdaled

**Comment by PopWarner** [comment]
Thank you for registering. You have been added to your chosen the session. A Microsoft Teams calendar invite has been sent out to all that have registered. Occasionally the invite will get placed into the spam, junk or bulk boxes, so if you don't see the invite, try double checking those boxes. 🙂

Please don't hesitate to reach out if you have not received the email invite. 🙂💜🧡

@fchopo
@ofuen

**Comment by ofuen** [comment]
Happy Friday @PopWarner , Check my inbox and junk boxes, Never received the invite.

**Comment by PopWarner** [comment]
Hi @ofuen, I’ll send you a DM and we can double check the email I have and maybe try a different one. :)

**Comment by PopWarner** [comment]
Session Completed. Thank you all for attending! 💜🧡

**Comment by westerdaled** [comment]
Thank you again David for making this fun learning session  ( even when I muddled my  files and folders😀) . Noticed somebody added my company name 😊when I caught up with the monthly community call video.
