### ISSUE TITLE
Sharing is Caring - rahulsuryawanshi

### ISSUE THREAD

**Issue by rahulsuryawanshi** [pnp/sharing-is-caring#145]
#### Article suggestion

 

It would be nice to add something about the **Sharing is Caring** initiative

**Comment by hugoabernier** [comment]
Thanks @rahulsuryawanshi you're assigned to it.

**Comment by PopWarner** [comment]
Thank you again for attending today! Excellent job on your contribution and PR! 🤗🧡💜
