### ISSUE TITLE
Sharing is caring - sinhakislay

### ISSUE THREAD

**Issue by sinhakislay** [pnp/sharing-is-caring#146]
#### Article suggestion

It would be nice to add something about the **Sharing is Caring** initiative.

I would like to take this, please assign this to me

**Comment by hugoabernier** [comment]
Thanks @sinhakislay you're assigned to it.

**Comment by PopWarner** [comment]
Thank you again for attending today! Excellent job on your contribution and PR! 🤗🧡💜
