### ISSUE TITLE
Sharing is Caring - annajhaveri

### ISSUE THREAD

**Issue by annajhaveri** [pnp/sharing-is-caring#148]
#### Article suggestion
It would be nice to add something about the **Sharing is Caring** initiative

i'd like to take this, please assign it to me

**Comment by hugoabernier** [comment]
Thanks @annajhaveri  you're assigned to it.

**Comment by PopWarner** [comment]
Thank you again for attending today! Excellent job on your contribution and PR! 🤗🧡💜
