### ISSUE TITLE
Sharing is Caring - kirti-prajpati

### ISSUE THREAD

**Issue by kirti-prajapati** [pnp/sharing-is-caring#149]
#### Article suggestion
It would be nice to add something about the *Sharing is Caring* initiative.
I'd like to take this. Please assign this to me.

**Comment by hugoabernier** [comment]
Thanks @kirti-prajapati you're assigned to it.

**Comment by PopWarner** [comment]
Thank you again for attending today! Excellent job on your contribution and PR! 🤗🧡💜
