### ISSUE TITLE
What to know about SharePoint Framework Certification.

### ISSUE THREAD

**Issue by Dhiru09** [pnp/sharing-is-caring#150]
> We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Question

> Have a question about this repository, how you might help, etc.? Use this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#
#### Submission Guidelines

> - All questions are welcome! Please let us know what's on your mind.
> - Try to include sufficient details and context. If you aren't clear, expect some dialog to refine the idea.
> - If you have multiple questions, please submit them in separate issues so we can track them to resolution separately.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
@Dhiru09, thanks for your questions but please make us proud next time you open an issue and take the time to **fill the template** -- after all, you're going to be a Sharing Is Caring graduate and we have a reputation to maintain 😁

I would recommend you follow the exam and certification roadmap outline here:
https://docs.microsoft.com/en-us/learn/certifications/m365-developer-associate

I hope this helps?

**Comment by PopWarner** [comment]
Thank you again for attending today @Dhiru09. Good job on the PR. :)
