### ISSUE TITLE
PnP - First Time Contributor Sessions - July 24th & 27th

### ISSUE THREAD

**Issue by PopWarner** [pnp/sharing-is-caring#172]
Hello PnP Contributors! 😉

If you would like to join a PnP Sharing Is Caring - First Time Contributor guidance session, please use the link below to select one of the scheduled sessions.

July 24th & 27th - Sharing is Caring - First Time Contributor Registration:
https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMThNRUxPQUtYRFk3TUw3MEE2UUc0R0JJOC4u

We know that schedules vary...so if you are unable to the sessions, not to worry!! There are more sessions scheduled each month. 😊

Thanks again for your collaborative community spirit!! 👍

You can also find all of the available scheduled sessions at:
https://aka.ms/sharing-is-caring#pnp-sic-events

cc: @hugoabernier

**Comment by PopWarner** [comment]
Thank you to all who have registered. A Microsoft Teams calendar invite has been sent out to all that have registered. Occasionally the invite will get placed into the spam, junk or bulk boxes, so if you don't see the invite, try double checking those boxes. 🙂

Please don't hesitate to reach out if you have not received the email invite. 🙂💜🧡

We look forward to seeing you all!!

@zenaidura
@phastafrican
@bencamino
@LuiseFreese
@ashiqf
@jshooper
@donshults
@alexabramkin
@donkirkham
@cmack00
@akashkarda
@srtweb
@Gezeitenbrand
@jpwegmuller50
@soludata
@cgjerde
@lamaisondescartes
@waelkanan
@NeverHere
@Ynot3363

**Comment by LuiseFreese** [comment]
Hey, this is great! Thank you for organizing this! Looking forward to meet you all, Luise

**Comment by PopWarner** [comment]
Thank you to all who attended Friday's First Time Contributor Session. If you were registered, but were unable to attend, you are free to drop in on today's session, which begins at 4pm PT. 🤗

[Direct Teams Link - 4pm PT](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OTZmOGEyYzEtMWVhOC00ZTFkLWI5NGQtYTcwNjQzMWMxNGQx%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)

If the time for today's session does not work for your schedule, not to worry, we will be publishing our August First Time Contributor session dates very soon. 🧡💜

Thank you all again for your willingness to contribute to the community! You are awesome!! 😍

@zenaidura
@phastafrican
@bencamino
@LuiseFreese
@ashiqf
@JSHooper
@donshults
@alexabramkin
@DonKirkham
@cmack00
@akashkarda
@srtweb
@Gezeitenbrand
@jpwegmuller50
@soludata
@cgjerde
@lamaisondescartes
@waelkanan
@NeverHere
@ynot3363

cc: @hugoabernier

**Comment by PopWarner** [comment]
Sessions completed. Thank you all for attending! 🧡💜
