### ISSUE TITLE
What is the difference between SPHttpClient , MSGraphClient, AADHttpClient ?? 

### ISSUE THREAD

**Issue by Dhiru09** [pnp/sharing-is-caring#192]
#### What is the difference between SPHttpClient , MSGraphClient, AADHttpClient ?? 

> 1. What is the difference between RestAPI and Microsoft Graph API ?
> 2. What is the difference between SPHttpClient , MSGraphClient, AADHttpClient ?
> 3. Please explain 2nd question based on scenario/example.

Thank you.

**Comment by hugoabernier** [comment]
Closing this issue. We should move this to the sp-dev-docs repo where it is best suited.
