### ISSUE TITLE
PopWarner - Sharing is Caring - Comm Docs

### ISSUE THREAD

**Issue by Warner-Digital** [pnp/sharing-is-caring#209]
#### Article suggestion			
It would be nice to add something about the **Sharing is Caring** initiative

Please assign this to me. I'd like to provide this document.

**Comment by hugoabernier** [comment]
Thanks @PopWarner  this is a great idea.  I have assigned this issue to you.

Looking forward to your article!

**Comment by Warner-Digital** [comment]
Documents submitted and PR Approved.
