### ISSUE TITLE
TesfayeGari -  Sharing is Caring -Comm Docs

### ISSUE THREAD

**Issue by tesfayegari** [pnp/sharing-is-caring#210]
#### Article suggestion

 

It would be nice to add something about the **Sharing is Caring** initiative

**Comment by hugoabernier** [comment]
Thanks @tesfayegari  this is a great idea.  I have assigned this issue to you.

Looking forward to your article!

**Comment by tesfayegari** [comment]
Document submitted and PR Approved

**Comment by PopWarner** [comment]
Thank you again for attending the SiC Session. You are awesome! 🧡💜
