### ISSUE TITLE
ofuen -  Sharing is Caring - Comm Docs

### ISSUE THREAD

**Issue by ofuen** [pnp/sharing-is-caring#212]
#### Article suggestion 
It would be nice to add something about the **Sharing is Caring** initiative

**Comment by hugoabernier** [comment]
Thanks @ofuen  this is a great idea.  I have assigned this issue to you.

Looking forward to your article!

**Comment by PopWarner** [comment]
Thank you again for attending the SiC Session. You are awesome! 🧡💜
