### ISSUE TITLE
akashkarda - Sharing is Caring - Comm Docs

### ISSUE THREAD

**Issue by akashkarda** [pnp/sharing-is-caring#213]
#### Article suggestion
It would be nice to add something about the **Sharing is Caring** initiative

**Comment by hugoabernier** [comment]
Thanks @akashkarda  this is a great idea.  I have assigned this issue to you.

Looking forward to your article!

**Comment by PopWarner** [comment]
Thank you again for attending the SiC Session. You are awesome! 🧡💜
