### ISSUE TITLE
BenCamino - Sharing is Caring - Comm Docs

### ISSUE THREAD

**Issue by bencamino** [pnp/sharing-is-caring#215]
#### Article suggestion
It would be nice to add something about the **Sharing is Caring** initiative

Please let me know if there is anything I can help with on this effort

**Comment by hugoabernier** [comment]
Thanks @bencamino  this is a great idea.  I have assigned this issue to you.

Looking forward to your article!

**Comment by PopWarner** [comment]
Thank you again for attending the SiC Session. You are awesome! 🧡💜
