### ISSUE TITLE
PnP - First Time Contributor Sessions - August 21st, 24th & 26th

### ISSUE THREAD

**Issue by PopWarner** [pnp/sharing-is-caring#223]
Hello PnP Contributors! 😉

If you would like to join a PnP Sharing Is Caring - First Time Contributor guidance session, please use the link below to select one of the scheduled sessions.

August 21st, 24th & 26th - Sharing is Caring - First Time Contributor Registration:
https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUOVhYTzM5VE1IWVJNUlEyUTQ0WDAyS0RCVi4u

We know that schedules vary...so if you are unable to the sessions, not to worry!! There are more sessions scheduled each month. 😊

Thanks again for your collaborative community spirit!! 👍

You can also find all of the available scheduled sessions at:
https://aka.ms/sharing-is-caring#pnp-sic-events

cc: @hugoabernier

**Comment by PopWarner** [comment]
Thank you to all who have registered. A Microsoft Teams calendar invite has been sent out to all that have registered. Occasionally the invite will get placed into the spam, junk, or bulk boxes, so if you don't see the invite, try double-checking those boxes. 🙂

Please don't hesitate to reach out if you have not received the email invite. 🙂💜🧡

I've also included direct links to each of the First Time Contributor Sessions below in case you did not receive the invite.

We look forward to seeing you all!!

@HansHWestphal
@LuiseFreese
@ab14jain
@Milan-Pro
@PawanJajoo
@ravick4u
@Gezeitenbrand
@JayneshSharma
@erkanch
@mikegil4
@sptechmk
@LeonArmston
@Manjunath2015
@merrilea
@kathyos
@lsmithmier

**Friday, Aug 21st:**
[Direct Teams Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGM2NzU4MDEtM2NiMS00OTY2LWI0YzgtZGIwYzdhOWU3ZmYx%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)


**Monday, Aug 24th:**
[Direct Teams Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YjQxZGI1YzYtNzkyMC00OWI2LWFjMjItMmI3Y2I5Y2FkYTYx%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)

**Wednesday, Aug 26th:**
[Direct Teams Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZWFlNTFlZTEtNTEyYS00MTYxLThlYjMtOTIwOTM3ZmFiNzEx%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)

**Comment by merrilea** [comment]
Good morning!

Thank you for this information!

I’ve had something come up and won’t be able to attend the session this Wednesday at 8 AM PST.

I was wondering if I could join in the 4PM PST time today instead? Or should I reschedule for another day?

Thank you!

Merrilea N. Price

**Comment by PopWarner** [comment]
@merrilea no problem! We'd love to see you this afternoon. 👍 

I've added your resource files for the session this afternoon and sent you an invite.

**Comment by merrilea** [comment]
Thank you so much! ☺

Merrilea

**Comment by PopWarner** [comment]
Looking forward to seeing everyone in our final Sharing is Caring First Time Contributor session tomorrow for the month August.

All who registered and referenced below should have received a Microsoft Teams calendar invite. If you did not, be sure to double-check your spam or junk boxes. 

You can also join the Team call directly using the following link. The session is at 8am PT.
[Direct Teams Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZWFlNTFlZTEtNTEyYS00MTYxLThlYjMtOTIwOTM3ZmFiNzEx%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)

You are all awesome! 💜🧡


@LuiseFreese
@Gezeitenbrand
@LeonArmston
@reddzman
@sptechmk
@RomanAtSogeti
@DikshaPoddar

cc: @hugoabernier

**Comment by PopWarner** [comment]
Thank you all for attending the August PnP Sharing is Caring session. You are awesome!!! 😍💜🧡
