### ISSUE TITLE
Question about contributing to forks

### ISSUE THREAD

**Issue by mikezimm** [pnp/sharing-is-caring#23]
@PopWarner ,
I had a question since the training...

I made a suggestion to SharePoint/sp-dev-fx-webparts (issue 1009).
The suggestion related to the [react-securitygrid sample](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-securitygrid).

1. russgove picked up the idea,[ created a fork](https://github.com/russgove/sp-dev-fx-webparts) and started working on it.
After I saw his fork, I had a new idea to make it work better so...

2. I forked his fork,
3. Made some updates to [my fork](https://github.com/mikezimm/sp-dev-fx-webparts/tree/dev)
4. Created a pull request back to his fork [my pull request](https://github.com/russgove/sp-dev-fx-webparts/pull/1)
5. Then made some more updates and apparently committed my second update to the pull request.

**So the question is:**
Because I forked his fork, does it show I contributed back in the sharepoint repo?  Or only the first person to fork that repo?

BTW, I think I need to go to the followup Sharing is Caring because I think I didn't get do my original pull request to his fork right ha ha ha.

**Comment by garrytrinder** [comment]
> Because I forked his fork, does it show I contributed back in the sharepoint repo? 

@mikezimm all depends on how your changes get merged back into the SharePoint repo unfortunately, so hard to really give you a definite answer. 

However for your scenario the best way to approach this would be to do the following...

- Create your own fork of the `sp-dev-fx-webparts` repo
- Clone your fork to your local machine
  - `git clone https://github.com/mikezimm/sp-dev-fx-webparts.git`
- Create a new remote pointing to russgove fork
  - `git remote add russgove https://github.com/russgove/sp-dev-fx-webparts.git`
- Pull down the branches from russgove remote
  - `git fetch russgove`
- Checkout russgove branch containing his changes
  - `git checkout russgove/feature-branch`
- Create a new branch from russgove branch for you to add your changes to
  - `git checkout -b your-feature-branch`
- Make your changes and commit them to your feature branch
- Push your feature branch to your fork
  - `git push`
- Create a pull request to the `sp-dev-fx-webparts` repo 

This approach enables you to pull a branch from another contributors fork into your own local repository, work on it, push that to your own fork and then submit the pull request from your fork.

**Comment by PopWarner** [comment]
Thanks all.. :)
