### ISSUE TITLE
Sharing is Caring - jpwegmuller50

### ISSUE THREAD

**Issue by jpwegmuller50** [pnp/sharing-is-caring#255]
#### Article suggestion			
It would be nice to add something about the **Sharing is Caring** initiative

**Comment by hugoabernier** [comment]
Thank you @jpwegmuller50 , I've got you assigned to this.

**Comment by PopWarner** [comment]
Thank you again for attending. Looking forward to collaborating with you on more contributions! 💜🧡

**Comment by jpwegmuller50** [comment]
Thanks, David.  Really appreciated your training.  You do a great job at
explaining things and making sure everyone is keeping up.
