### ISSUE TITLE
Community Docs Sample - Manjunath2015

### ISSUE THREAD

**Issue by Manjunath2015** [pnp/sharing-is-caring#270]
#### Article suggestion			
It would be nice to add something about the **Sharing is Caring** initiative

**Comment by hugoabernier** [comment]
Thank you @Manjunath2015 , I've assigned this issue to you.

**Comment by PopWarner** [comment]
Thank you again for attending. Looking forward to collaborating with you on more contributions! 💜🧡

**Comment by Manjunath2015** [comment]
Happy to collaborate and looking forward for  to contribute for sharing is caring community.

Thanks to David and hugho for providing wonderfull sessions Sharing is caring
