### ISSUE TITLE
PnP - SPFx Samples using Node Version Manager - Sept 11th, 15th & 29th

### ISSUE THREAD

**Issue by PopWarner** [pnp/sharing-is-caring#291]
Hello PnP Contributors! 😉

If you would like to join a PnP Sharing Is Caring - "PnP SPFx Samples - Solving SPFx version differences using Node Version Manager" guidance session, please use the link below to select one of the scheduled sessions.

Sept 11th, 15th & 29th- Sharing is Caring - SPFx Samples using Node Version Manager:
[Session Registration Form](https://forms.microsoft.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUODNCNDlZS0RDMUMzUzVRT1dET0FCMFpYUi4u)

We know that schedules vary...so if you are unable to the sessions, not to worry!! There are more sessions scheduled each month. 😊

Thanks again for your collaborative community spirit!! 👍

You can also find all of the available scheduled sessions at:
https://aka.ms/sharing-is-caring#pnp-sic-events

cc: @hugoabernier

**Comment by PopWarner** [comment]
Thank you to all who have registered for the September 11th PnP SPFx Samples using NVM session.

A Microsoft Teams calendar invite has been sent out to all that have registered. Occasionally the invite will get placed into the spam, junk, or bulk boxes, so if you don't see the invite, try double-checking those boxes. 🙂

Please don't hesitate to reach out if you have not received the email invite. 🙂💜🧡

I've also included a direct link to the session below in case you did not receive the invite.
[September 11th Direct Teams Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDk5NmJmMzEtNTRjNy00OTMzLWFjZjEtMWU1NDRjZmY5MzY1%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)

We look forward to seeing you all!!


@jonesron
@zenaidura
@Manjunath2015
@mariosaccoia
@sdhayward
@gauravgoyal5
@JayneshSharma
@jeremyBass

cc: @hugoabernier

**Comment by PopWarner** [comment]
Thank you to all who have registered for the **September 15th & 29th** PnP SPFx Samples using NVM session.

A Microsoft Teams calendar invite has been sent out to all that have registered. Occasionally the invite will get placed into the spam, junk, or bulk boxes, so if you don't see the invite, try double-checking those boxes. 🙂

Please don't hesitate to reach out if you have not received the email invite. 🙂💜🧡

I've also included a direct link to the sessions below in case you did not receive the invite.

### Direct Teams Links:
[September 15th Direct Teams Link - 4pm PT](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjFmMDc0OTktMzVkNC00YjAzLTg1YjUtM2Q2OWJiNmU5NzA2%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)

[September 29th Direct Teams Link - 4pm PT](https://teams.microsoft.com/l/meetup-join/19%3ameeting_Y2YxYmNlNWYtODVkMy00NWIzLThhNzMtM2I0OGFiY2FkYjI5%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)

We look forward to seeing you all!!

@6gal6ler6
@soludata
@divya-akula
@bigpix2000
@merrilea

cc: @hugoabernier

**Comment by PopWarner** [comment]
**September 11th** PnP SPFx Samples using NVM session update.

Thank you to all who have registered.

A Microsoft Teams calendar invite has been sent out to all that have registered. Occasionally the invite will get placed into the spam, junk, or bulk boxes, so if you don't see the invite, try double-checking those boxes. 🙂

Please don't hesitate to reach out if you have not received the email invite. 🙂💜🧡

I've also included a direct link to the session below in case you did not receive the invite.
[September 11th Direct Teams Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDk5NmJmMzEtNTRjNy00OTMzLWFjZjEtMWU1NDRjZmY5MzY1%40thread.v2/0?context=%7b%22Tid%22%3a%22da32d22a-0bf8-445b-8e81-96f0bd0b9169%22%2c%22Oid%22%3a%2229c8d770-0e7d-4740-ab80-36386eee2e97%22%7d)

We look forward to seeing you all!!



@Girish1311
@Akshay7143
@himanshu
@ashiqf
@DonKirkham
@bjkline
@manoj1201
@phastafrican
@a1mery

**Comment by bigpix2000** [comment]
Hi Dave .... please resend the invite?  Thanks ..... not sure where it went (I forward it always to my Main work account but this time it's not there either)  Thanks


Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by PopWarner** [comment]
@bigpix2000, I just re-forwarded it to both of your emails. It looks like you already had sent it to your main work account. You used your personal address on the registration.

FYI: I edited your original message as it looks like you replied via email. Remember to use that "edit it on GitHub" link or the mobile GitHub app... 😁

**Comment by bigpix2000** [comment]
That's why I could not find it .... 6 PM central not 6 AM :(  sheeesh .... my calendar view was bocking it.  fixed it (and reminded me that my user group meets the day after on power platform stuff) .... we are good thanks!

RR


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by PopWarner** [comment]
Thank you all for attending! If you were unable to attend and would like to attend a future session, October events have been scheduled and can be registered at https://aka.ms/sharing-is-caring#pnp-sic-events
