### ISSUE TITLE
PnP First Time Contributor Session Scheduling - January 2020

### ISSUE THREAD

**Issue by PopWarner** [pnp/sharing-is-caring#33]
Hello, future PnP Contributors! 😉

All those referenced below should have received an email with instructions and a link to select one of two scheduled "PnP First Time Contributor" January 2020 sessions. Please let me know if you did not receive it.

We know that schedules vary...so if you are unable to make any of the sessions for this month, not to worry, we are already working on schedule the February sessions. 😊

Please be sure to check your spam or junk boxes just in case it gets flagged as such.

Thanks again for your collaborative community spirit!! 👍

@TheAndrewHess, @josephjtsoleraincdev, @Armachillo, @troystaylor, @datocrats-org, @ashiqf, @kiransripada, @willholland, @JMTeamway, @arunkumarperumal, @juanbriceno, @PrasadKasireddy, @rsperre, @Kasperbolarsen, @RohitSPatil, @superlena, @shakykhan, @wwcoop, @bigpix2000 @hugoabernier

**Comment by rsperre** [comment]
Hi

I can't find the mentioned invitation anywhere unfortunately. Could you
please try to resend it?

-Rune Sperre

**Comment by PopWarner** [comment]
Hi everyone.

I wanted to clarify regarding the email that went out. The email that went out was to select you're desired time for the January session(s).

The email that includes the Teams invite will be going out today. :)

If you have not received yet the email with the link to select your desired session, please definitely let me know and we will ensure you get the form URL. 👍  

@JMTeamway (Julien), I see you registered for one of the January session. Were you referring to the Teams invite email? :)

Thank you all again and looking forward to the sessions.

**Comment by wwcoop** [comment]
How long is the session? (1 hour?)

Will Cooper

**Comment by PopWarner** [comment]
@wwcoop, correct, it lasts about 1 hour. 👍

**Comment by JMTeamway** [comment]
Hi,

Things are ok for me as I am registrered for january session.
My colleague @MCTeamway<https://github.com/MCTeamway> has registrered too but I don’t see his name in the list you provided.
Should he use the form to register again ?



Cordialement,

Julien MAGNE
Chef de projet - R&D

Email : julien.magne@teamway.fr<mailto:julien.magne@teamway.fr>

Téléphone : +336 82 23 25 22
[logo_teamway]
________________________________

De : David Warner II <notifications@github.com>
Envoyé : mardi 21 janvier 2020 15:11
À : pnp/sharing-is-caring <sharing-is-caring@noreply.github.com>
Cc : Julien MAGNE <julien.magne@teamway.fr>; Mention <mention@noreply.github.com>
Objet : Re: [pnp/sharing-is-caring] PnP First Time Contributor Session Scheduling - January 2020 (#33)


Hi everyone.

I wanted to clarify regarding the email that went out. The email that went out was to select you're desired time for the January session(s).

The email that includes the Teams invite will be going out today. :)

If you have not received yet the email with the link to select your desired session, please definitely let me know and we will ensure you get the form URL. 👍

@JMTeamway<https://github.com/JMTeamway> (Julien), I see you registered for one of the January session. Were you referring to the Teams invite email? :)

Thank you all again and looking forward to the sessions.

**Comment by MCTeamway** [comment]
Hi I ‘m Maxime Combeau from Teamway,

I received this notification so i guess i’m part of the list 😊

De : JMTeamway <notifications@github.com>
Envoyé : mardi 21 janvier 2020 15:17
À : pnp/sharing-is-caring <sharing-is-caring@noreply.github.com>
Cc : Maxime COMBEAU <maxime.combeau@teamway.fr>; Mention <mention@noreply.github.com>
Objet : Re: [pnp/sharing-is-caring] PnP First Time Contributor Session Scheduling - January 2020 (#33)

Hi,

Things are ok for me as I am registrered for january session.
My colleague @MCTeamway<https://github.com/MCTeamway> has registrered too but I don’t see his name in the list you provided.
Should he use the form to register again ?



Cordialement,

Julien MAGNE
Chef de projet - R&D

Email : julien.magne@teamway.fr<mailto:julien.magne@teamway.fr>

Téléphone : +336 82 23 25 22
[logo_teamway]
________________________________

De : David Warner II <notifications@github.com>
Envoyé : mardi 21 janvier 2020 15:11
À : pnp/sharing-is-caring <sharing-is-caring@noreply.github.com>
Cc : Julien MAGNE <julien.magne@teamway.fr>; Mention <mention@noreply.github.com>
Objet : Re: [pnp/sharing-is-caring] PnP First Time Contributor Session Scheduling - January 2020 (#33)


Hi everyone.

I wanted to clarify regarding the email that went out. The email that went out was to select you're desired time for the January session(s).

The email that includes the Teams invite will be going out today. :)

If you have not received yet the email with the link to select your desired session, please definitely let me know and we will ensure you get the form URL. 👍

@JMTeamway<https://github.com/JMTeamway> (Julien), I see you registered for one of the January session. Were you referring to the Teams invite email? :)

Thank you all again and looking forward to the sessions.

**Comment by PopWarner** [comment]
@JMTeamway...thank you for the update. :)

Hi @MCTeamway (Maxime)...welcome!!

I checked the master list for all registrations and I don't see you're information having been submitted yet.

Can you fill out the following form and I will get you an email with information on choosing one of the January sessions:
https://forms.office.com/Pages/ResponsePage.aspx?id=P4W00MjlVkqb2oRWF2ZrgX11OyUhMWtHhZR7nphQCrdUNjc4NkdGUzZETElaUThNV0JZVVZXQzdOTC4u

**Comment by PopWarner** [comment]
Hi @MCTeamway, I wanted to follow up and make sure we get you into the session. I sent a connection request to you via LinkedIn to allow us to directly communicate if needed. :)

**Comment by PopWarner** [comment]
Happy Friday everyone! 

The email calendar invites with the Microsoft Team meeting link for next week's sessions have been sent out. Please let me know if you have do not get the email. 👍😊

Looking forward to seeing you all on the sessions...you rock!! 🧡💜

**Comment by arunkumarperumal** [comment]
I haven't received the meeting invite for this week's meeting.

Can you please share again.

Regards,
Arun

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by PopWarner** [comment]
Hi @arunkumarperumal, glad we got you taken care of. See you tomorrow. 👍  🙂

**Comment by PopWarner** [comment]
We are looking forward to our Sharing Is Caring First Time Contributors session's tomorrow. 

Please let me know if you have not received the email invite.

Thanks all!

**Comment by jindalv10** [comment]
@PopWarner 

Hi David, 

I would like to submit PR for Datetime issue raised by in following link:
 https://github.com/SharePoint/sp-dev-fx-webparts/issues/1115

I have also updated the SPFx version of the project. How do I submit closed issue PR?

Thanks
Varun

**Comment by PopWarner** [comment]
Session Completed. 👍 Thank you everyone who joined!

**Comment by JMTeamway** [comment]
Julien MAGNE a partagé "Invoice-030440" avec vous.




















This link only works for the direct recipients of this message.











Julien MAGNE








Open





































Microsoft respects your privacy. To learn more, please read our Privacy
 Statement.
Microsoft Corporation, One Microsoft Way, Redmond, WA 98052

Unsubscribe from
 share reminder emails.

**Comment by bigpix2000** [comment]
Looks like an auto post test?
