### ISSUE TITLE
Sharing is Caring Dbroussa

### ISSUE THREAD

**Issue by dbroussa** [pnp/sharing-is-caring#345]
#### Article suggestion			
It would be nice to add something about the **Sharing is Caring** initiative

**Comment by dbroussa** [comment]
I would like to be assigned to this

**Comment by hugoabernier** [comment]
@dbroussa this is a great idea for an article! I have _gone ahead_ and assigned the article to you.

**Comment by PopWarner** [comment]
Thanks again for joining us! We look forward to seeing you at future Sharing is Caring sessions! 💜🧡
