### ISSUE TITLE
Sharing Is Caring - muralidharand

### ISSUE THREAD

**Issue by muralidharand** [pnp/sharing-is-caring#346]
#### Article suggestion			
It would be nice to add something about the **Sharing is Caring** initiative

**Comment by hugoabernier** [comment]
@muralidharand this is a great idea for an article! I have _gone ahead_ and assigned the article to you.

**Comment by muralidharand** [comment]
I would like to be assigned to this.

**Comment by PopWarner** [comment]
Thanks again for joining us! We look forward to seeing you at future Sharing is Caring sessions! 💜🧡
