### ISSUE TITLE
bigpix2000 sharing is caring

### ISSUE THREAD

**Issue by bigpix2000** [pnp/sharing-is-caring#347]
#### Article suggestion			
It would be nice to add something about the **Sharing is Caring** initiative

**Comment by bigpix2000** [comment]
and remember to credit Hugo for all his work

**Comment by hugoabernier** [comment]
@bigpix2000 this is a great idea for an article! I have _gone ahead_ and assigned the article to you.

**Comment by bigpix2000** [comment]
#346 may be related to this

**Comment by PopWarner** [comment]
Thanks again for joining us! We look forward to seeing you at future Sharing is Caring sessions! 💜🧡
