### ISSUE TITLE
PnP First Time Contributor Session Scheduling - February 2020

### ISSUE THREAD

**Issue by PopWarner** [pnp/sharing-is-caring#46]
Hello, future PnP Contributors! 😉

All those referenced below should be receiving an email with instructions and a link to select one of two scheduled "PnP First Time Contributor" February 2020 sessions. 

Please be sure to check your spam or junk boxes just in case it gets flagged as such.

For any that have not already registered to be updated on future sessions, you can register directly here:
https://forms.microsoft.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdURVVVNTdKR1YzOEZSQU5PNzZRRjZVRzJCRi4u

We know that schedules vary...so if you are unable to make any of the sessions for this month, not to worry, we are already working on schedule the March sessions. 😊

Thanks again for your collaborative community spirit!! 👍

@TheAndrewHess @josephjtsoleraincdev @Armachillo @troystaylor @datocrats-org @kiransripada @WeeTeck @willholland @juanbriceno @shakykhan @RohitSPatil @superlena @sheedydan @nhimanshu17 @george-tymvios @robiharid @sjha2707 @Harshagracy @jagsridharan

**Comment by PopWarner** [comment]
Hello everyone! :) 

Invites for this week's two Sharing Is Caring session's have been emailed and will include a Teams invite for your chosen timeslot. Please let me know if you did not receive it. 😁

There is also still time for anyone that would like to join who has not yet registered. Please use the Office Forms link in the first message and register. We would love to have you join!

@sjha2707
@juanbriceno
@sachinjha15
@jagsridharan
@Harshagracy
@theresaeller
@a1mery
@nhimanshu17

**Comment by george-tymvios** [comment]
Good morning @PopWarner , I can't seem to find the meeting invite. Do you mind sending it again?

**Comment by PopWarner** [comment]
Hi @george-tymvios! Hope all is well. 

I don’t show that you registered for one of the available time slots. 

If you visit the forms link in the first post on this issue and select one of the two available time slots, I can send you the invite for the time you choose. :)

**Comment by george-tymvios** [comment]
My bad :) I thought it was the form I completed already. Registered now.

**Comment by PopWarner** [comment]
Thanks @george-tymvios! Got your registration and will get the invite out to you first thing in my am. 👍🏻

Looking forward to seeing you at the session. 😁

**Comment by PopWarner** [comment]
Thanks again @george-tymvios. I've sent you the invite. Please let me know if it didn't arrive? :)

**Comment by george-tymvios** [comment]
Thank you @PopWarner. I received and accepted the invitation :)

**Comment by Harshagracy** [comment]
Hi @PopWarner,  Accepted the invitation and looking forward to the session.

**Comment by PopWarner** [comment]
@rshirpuram, Got your registration and added you to the Teams invite. Let me know if you did not get it. :)

**Comment by rshirpuram** [comment]
@PopWarner Received! Thanks for the invite David.

**Comment by PopWarner** [comment]
@pradip-cyclotron, I got your registration and added you to the Teams invite. Please let me know if you did not get it. 🙂

**Comment by PopWarner** [comment]
@corriespondent
@ThomasLamb

Thank you both for registering. I have emailed you the Teams invite for your chosen session. Please let me know if you do not get it.  🙂

**Comment by PopWarner** [comment]
@sinhakislay

Thank you for your registration! I have added you to the Teams email invite. Please let me know if you do not get it. 🙂

**Comment by PopWarner** [comment]
Session Completed. 👍 Thank you everyone who joined!
