### ISSUE TITLE
Sharing is Caring - Comm Docs Demo - WarnerDigital

### ISSUE THREAD

**Issue by Warner-Digital** [pnp/sharing-is-caring#483]
#### Article suggestion			
It would be nice to add something about the **Sharing is Caring** initiative

Please assign me to this issue

**Comment by hugoabernier** [comment]
Great idea @Warner-Digital 

![Great idea](https://media3.giphy.com/media/Y4nmq4GOnLf4XIgALX/giphy.gif)

I've gone ahead and assigned you to this article. Can't wait to see what you come up with!
