### ISSUE TITLE
More Markdown sample if any?

### ISSUE THREAD

**Issue by metro-mark** [pnp/sharing-is-caring#486]
Any markdown sample and tutorial may be helpful

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
Great idea @metro-mark 

I've gone ahead and assigned you to this article. Can't wait to see what you come up with!

**Comment by hugoabernier** [comment]
I personally enjoy https://stackabuse.com/markdown-by-example/ as a great way to learn Markdown.
