### ISSUE TITLE
PnP First Time Contributor Session Scheduling - November

### ISSUE THREAD

**Issue by PopWarner** [pnp/sharing-is-caring#5]
Hello, future PnP Contributors! 😉

All those referenced below should be receiving an email today with instructions and a link to select one of two scheduled "PnP First Time Contributor" November sessions. Please let me know if you do not receive it.

Please be sure to check your spam or junk boxes just in case it gets flagged as such.

Thanks again for your collaborative community spirit!! 👍

David

@arjunumenon,@LouFarho,@TheAndrewHess,@arnostac,@josephjtsoleraincdev,@rahulsuryawanshi,@westerdaled,@bricenocar,@amit12joshi,@troystaylor,@billbrockbank,@datocrats-org,@ValerasNarbutas,@CindyRay,@ashiqf,@McDKirra,@mikezimm,@kiransripada,@WeeTeck

**Comment by ValerasNarbutas** [comment]
hey, thanks, registered, 
was this intentional :)
![image](https://user-images.githubusercontent.com/16476453/68930441-1317bb80-0797-11ea-9f80-f64302ef6ed7.png)

**Comment by ValerasNarbutas** [comment]
Thanks, registered.

**Comment by mikezimm** [comment]
7am PST,
Thanks!

**Comment by CindyRay** [comment]
David,I did not get the email with the link.  I have checked my trash and spam folders.  Can you please resend?
Thank you,
Cindy Bennight
    On Thursday, November 14, 2019, 02:19:32 PM CST, David Warner II <notifications@github.com> wrote:  
 
 
Hello, future PnP Contributors! 😉
 
All those referenced below should be receiving an email today with instructions and a link to select one of two scheduled "PnP First Time Contributor" November sessions. Please let me know if you do not receive it.

Please be sure to check your spam or junk boxes just in case it gets flagged as such.

Thanks again for your collaborative community spirit!! 👍
 
David

@arjunumenon,@LouFarho,@TheAndrewHess,@arnostac,@josephjtsoleraincdev,@rahulsuryawanshi,@westerdaled,@bricenocar,@amit12joshi,@troystaylor,@Billbrockbank,@datocrats-org,@ValerasNarbutas,@CindyRay,@ashiqf,@McDKirra,@mikezimm,@kiransripada,@weeteck

**Comment by PopWarner** [comment]
Hi @CindyRay. I went ahead and sent you an email back with a copy of the email. It looks like a different email was provided to the original form then what looks to be here on your GitHub account. Let me know if you get the email to the new address? :)

Thanks again for your interest and willingness to contribute! 👍

**Comment by bricenocar** [comment]
Hello david, i have not received it. Can you please resend it?

**Comment by PopWarner** [comment]
Hi @bricenocar, thanks for your message. 

Can you send me a message on twitter or linked in and I can be sure to get you the email directly. :)

Twitter: https://twitter.com/davidwarnerii
LinkedIn: https://www.linkedin.com/in/davidwarnerii/

Thanks again for your community collaborative spirit! 👍

**Comment by PopWarner** [comment]
For all those that have selected one of the two scheduled options, you will be receiving an email invite tomorrow for your chosen time.

For anyone who is unable to attend either of the two options, you will remain on the list for future sessions and I will continue to keep you updated with each month's options.

As always, feel free to reach out to me directly with any feedback and questions!

You are all awesome!! 👍

**Comment by PopWarner** [comment]
I hope everyone is having a fantastic week. 

I wanted to let everyone who registered for one of the PnP Sharing is Caring First-Time Contribution sessions know that the email invites have been sent, which includes the Teams meeting link. Please let me know if you have not received it. 👍 

Looking forward to seeing you all on Friday! :)

@troystaylor, @rahulsuryawanshi, @billbrockbank, @mikezimm, @arjunumenon, @ValerasNarbutas, @amit12joshi, @westerdaled, @LouFarho, @CindyRay
