### ISSUE TITLE
Power Automate should be capitalized

### ISSUE THREAD

**Issue by hugoabernier** [pnp/sharing-is-caring#689]
#### Article issue

The article on Power Automate spells it in lowercase, which is wrong. Power Automate is a brand name and should always be capitalized.

![Angry](https://memesbams.com/wp-content/uploads/2017/12/i-am-not-mad-just-very-very-angry-meme-37298.jpg)

**Comment by calebmil** [comment]
Hugo "bear"nier is at it again
